insert into tRenkler(Adi) values ('Mavi')
insert into tBoylar(Adi) values ('10')
insert into tAracTurleri(Adi) values ('Ucak')
insert into tUrunler (Adi, renk_tRenklerID, boy_tBoylarID, Arac, Fiyat) values ('Ucagým',1,1,1,55)
insert into tMusteriler(Adi) values ('Merve')
insert into tSatislar (Urun,Musteri) values (1,1)